web/router.ex
defmodule Juru.Router do
  use Juru.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Juru do
    pipe_through :browser # Use the default browser stack

    get "/", TransactionController, :new
    post "/create", TransactionController, :create, as: :transaction

    get "/assets", AssetController, :index
    get "/assets/new", AssetController, :new
    post "/assets/create", AssetController, :create

    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
    get "/logout", SessionController, :delete, as: :logout
    delete "/logout", SessionController, :delete, as: :logout
  end

  # Other scopes may use custom stacks.
  # scope "/api", Juru do
  #   pipe_through :api
  # end
end

lib/juru/auth.ex
defmodule Juru.Auth do
  import Plug.Conn
  import Ecto.Query

  alias Juru.User

  def init(opts) do
    Keyword.fetch!(opts, :repo)
  end

  def call(conn, repo) do
    user_id = get_session(conn, :user_id)

    cond do
      user = user_id && repo.get(User, user_id) ->
        put_current_user(conn, user)
      true ->
        assign(conn, :current_user, nil)
    end
  end

  defp put_current_user(conn, user) do
    token = Phoenix.Token.sign(conn, "user socket", user.id)

    conn
    |> assign(:current_user, user)
    |> assign(:user_token, token)
  end

  def login(conn, user) do
    conn =
      conn
      |> put_current_user(user)
      |> put_session(:user_id, user.id)
      |> configure_session(renew: true)
    conn
  end

  def logout(conn) do
    configure_session(conn, drop: true)
  end

  def login_by_name(conn, name, opts) do
    repo = Keyword.fetch!(opts, :repo)
    user = from(u in User, where: fragment("lower(name) = ?", ^String.downcase(name))) |> repo.one()

    cond do
      user ->
        {:ok, login(conn, user)}
      true ->
        {:error, :not_found, conn}
    end
  end
end

lib/juru/endpoint.ex
defmodule Juru.Endpoint do
  use Phoenix.Endpoint, otp_app: :juru

  socket "/socket", Juru.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :juru, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_juru_key",
    signing_salt: "Pn6deLja"

  plug Juru.Router
end

lib/juru/repo.ex
defmodule Juru.Repo do
  use Ecto.Repo, otp_app: :juru
end

web/models/asset.ex
defmodule Juru.Asset do
  use Juru.Web, :model

  schema "assets" do
    field :asset_id, :string
    field :name, :string
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:asset_id, :name])
    |> validate_required([:asset_id, :name])
  end
end

web/models/user.ex
defmodule Juru.User do
  use Juru.Web, :model

  schema "users" do
    field :name, :string
    field :public_key, :string
    field :private_key, :string
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :public_key, :private_key])
    |> validate_required([:name, :public_key, :private_key])
  end
end

web/controllers/asset_controller.ex
defmodule Juru.AssetController do
  use Juru.Web, :controller
  import Ecto.Query

  alias Juru.Asset

  plug Juru.Auth, [repo: Juru.Repo]

  def index(conn, _) do
    assets = Repo.all(Asset)

    # res = HTTPoison.get("localhost:8080/getAssets")

    query = from a in Asset, where: a.asset_id in ^["777a6ae6c05b47ffaf409c0fdd8a54fcf826dfb86b29b6bc6a03dacd0fe2fe85"]
    assets = Repo.all(query)

    render(conn, "index.html", assets: assets)
  end

  def new(conn, _) do
    render(conn, "new.html")
  end

  def create(conn, asset = %{"asset" => %{"name" => name, "content" => %Plug.Upload{path: path}}}) do
    user = conn.assigns[:current_user]
    IO.inspect(path)
    # payload = %{"asset" => %{"document" => asset}, "recipientPublicKey" => user.public_key, "recipientPrivateKey" => user.private_key}
    # res = HTTPoison.post("localhost:8080/createAsset", Poison.encode!(payload), [{"Content-Type", "application/json"}])

    res = {:ok, %HTTPoison.Response{status_code: 200, body: Poison.encode!(%{"id" => "123456"})}}

    case res do
      {:ok, %HTTPoison.Response{status_code: 200, body: body}} ->
        payload = Poison.decode!(body)
        chgs = Asset.changeset(%Asset{}, %{name: name, asset_id: payload["id"]})
        Repo.insert!(chgs)
      {:ok, _} ->
        nil
    end

    redirect(conn, to: asset_path(conn, :index))
  end
end

web/controllers/page_controller.ex
defmodule Juru.Controller do
  use Juru.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/session_controller.ex
defmodule Juru.SessionController do
  use Juru.Web, :controller

  def new(conn, _) do
    render(conn, "new.html")
  end

  def create(conn, %{"session" => %{"name" => name}}) do
    case Juru.Auth.login_by_name(conn, name, repo: Repo) do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "Hello blockchain citizen!")
        |> redirect(to: transaction_path(conn, :new))
      {:error, _reason, conn} ->
        conn
        |> put_flash(:error, gettext("User unknow"))
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> Juru.Auth.logout()
    |> put_flash(:info, gettext("You have been logged out"))
    |> redirect(to: transaction_path(conn, :new))
  end
end

web/controllers/transaction_controller.ex
defmodule Juru.TransactionController do
  use Juru.Web, :controller

  alias Juru.Asset

  plug Juru.Auth, [repo: Juru.Repo]

  def new(conn, _) do
    # get all my assets
    assets =
      Repo.all(Asset)
      |> Enum.map(&{&1.name, &1.asset_id})

    render(conn, "new.html", assets: assets)
  end

  def create(conn, %{"transaction" => %{"asset_id" => asset_id, "to" => to}}) do
    user = conn.assigns[:current_user]
    # payload = %{"assetId" => , "signingPrivateKey" => user.private_key, "recipientPublicKey" => to}
    # res = HTTPoison.post("localhost:8080/createAsset", Poison.encode!(payload), [{"Content-Type", "application/json"}])

    res = {:ok, %HTTPoison.Response{status_code: 200, body: Poison.encode!(%{"id" => "123456"})}}

    case res do
      {:ok, %HTTPoison.Response{status_code: 200, body: body}} ->
        # payload = Poison.decode!(body)
        conn
        |> put_flash(:info, "Great success")
        |> redirect(to: asset_path(conn, :index))
      _ -> render(conn, "new.html")
    end

  end
end

web/views/asset_view.ex
defmodule Juru.AssetView do
  use Juru.Web, :view
end

web/views/error_view.ex
defmodule Juru.ErrorView do
  use Juru.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Juru.LayoutView do
  use Juru.Web, :view
end

web/views/page_view.ex
defmodule Juru.PageView do
  use Juru.Web, :view
end

web/views/session_view.ex
defmodule Juru.SessionView do
  use Juru.Web, :view
end

web/views/transaction_view.ex
defmodule Juru.TransactionView do
  use Juru.Web, :view
end

web/templates/asset/index.html.eex
<ul>
  <%= for asset <- @assets do %>
    <li><%= asset.asset_id %><br /><%= asset.name %></li>
  <% end %>
</ul>

<p class="text-center">
  <a class="btn btn-primary" href="/assets/new">New Asset</a>
</p>

web/templates/asset/new.html.eex
<%= form_for @conn, asset_path(@conn, :create), [as: :asset, multipart: true], fn f -> %>
  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :content, class: "control-label" %>
    <%= file_input f, :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Juru!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/phoenix.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="/">Transactions</a></li>
            <li><a href="/assets">Assets</a></li>
            <%= if (@conn.assigns[:current_user]) do %>
              <li>Hello <%= @conn.assigns[:current_user].name %> (<a href="/logout" style="display: inline-block;">logout</a>)</li>
            <% else %>
              <li><a href="/login">login</a></li>
            <% end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/session/new.html.eex
<div class="container-fluid">
  <div class="row">
  <div class="col-sm-12">
  <%= form_for @conn, login_path(@conn, :create), [as: :session], fn f -> %>
    <div class="form-group ">
      <div class="input-group input-group-lg">
        <%= text_input f, :name, placeholder: "Name", class: "form-control" %>
      </div>
    </div>
    <div class="form-group ">
      <button type="submit" class="btn btn-primary btn-lg">Sign in</button>
    </div>
  <% end %>
  </div>
  </div>
</div>

web/templates/transaction/index.html.eex
All the transactions

web/templates/transaction/new.html.eex
<h4>Transfer your asset</h4>
<%= form_for @conn, transaction_path(@conn, :create), [as: :transaction, multipart: true], fn f -> %>
  <div class="form-group">
    <%= label f, :asset, class: "control-label" %>
    <%= select(f, :role, @assets) %>
  </div>

  <div class="form-group">
    <%= label f, :to, class: "control-label" %>
    <%= text_input f, :to, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>